# Generated by Django 6.0.8 on 2026-09-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('imdb_id', models.CharField(max_length=20, verbose_name='IMDb ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('poster', models.URLField(blank=True, max_length=500, verbose_name='poster')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='ano')),
                ('type', models.CharField(blank=True, max_length=10, verbose_name='tipo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'favorito',
                'verbose_name_plural': 'favoritos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'imdb_id'), name='favorito_unico_por_perfil')],
            },
        ),
    ]
