# Generated by Django 6.0.8 on 2026-09-13 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('avatar', models.CharField(choices=[('azul', 'Azul'), ('ciano', 'Ciano'), ('verde', 'Verde'), ('laranja', 'Laranja'), ('roxo', 'Roxo'), ('vermelho', 'Vermelho')], default='azul', max_length=20, verbose_name='avatar')),
                ('is_kids', models.BooleanField(default=False, verbose_name='perfil infantil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='perfil_unico_por_usuario')],
            },
        ),
    ]
