# Generated by Django 6.0.8 on 2026-09-13 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('event_type', models.CharField(choices=[('login_success', 'Login bem-sucedido'), ('login_failed', 'Falha de login'), ('login_blocked', 'Login bloqueado por rate limit'), ('signup', 'Cadastro realizado'), ('password_reset_requested', 'Recuperação de senha solicitada'), ('password_reset_completed', 'Senha redefinida'), ('email_confirmed', 'E-mail confirmado'), ('rate_limit_blocked', 'Ação bloqueada por rate limit'), ('player_access', 'Acesso ao player'), ('player_denied', 'Acesso ao player negado')], max_length=40, verbose_name='tipo de evento')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='rota')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'evento de segurança',
                'verbose_name_plural': 'eventos de segurança',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_securi_event_t_e93b36_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_securi_ip_addr_183a8e_idx')],
            },
        ),
    ]
