# Generated by Django 6.0.8 on 2026-09-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('imdb_id', models.CharField(max_length=20, verbose_name='IMDb ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('poster', models.URLField(blank=True, max_length=500, verbose_name='poster')),
                ('type', models.CharField(blank=True, max_length=10, verbose_name='tipo')),
                ('season', models.PositiveIntegerField(blank=True, default=0, verbose_name='temporada')),
                ('episode', models.PositiveIntegerField(blank=True, default=0, verbose_name='episódio')),
                ('progress_seconds', models.PositiveIntegerField(default=0, verbose_name='progresso (segundos)')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='duração (segundos)')),
                ('percent', models.FloatField(default=0, verbose_name='percentual concluído')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'histórico de visualização',
                'verbose_name_plural': 'históricos de visualização',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'imdb_id', 'season', 'episode'), name='progresso_unico_por_episodio')],
            },
        ),
    ]
