# Generated by Django 6.0.8 on 2026-09-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('is_kids_allowed', models.BooleanField(default=True, verbose_name='permitido para perfil infantil')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CuratedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('imdb_id', models.CharField(max_length=20, verbose_name='IMDb ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem no carrossel')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque no banner principal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='catalog.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'título curado',
                'verbose_name_plural': 'títulos curados',
                'ordering': ['category__order', 'order'],
                'constraints': [models.UniqueConstraint(fields=('category', 'imdb_id'), name='titulo_unico_por_categoria')],
            },
        ),
    ]
