# Generated by Django 6.0.8 on 2026-09-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('to_email', models.EmailField(max_length=254, verbose_name='destinatário')),
                ('email_type', models.CharField(choices=[('confirmation', 'Confirmação de e-mail'), ('welcome', 'Boas-vindas'), ('password_reset', 'Recuperação de senha'), ('password_changed', 'Alteração de senha')], max_length=30, verbose_name='tipo')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Não enviado (sem configuração)')], max_length=20, verbose_name='status')),
                ('provider_message_id', models.CharField(blank=True, max_length=100, verbose_name='id da mensagem no provedor')),
                ('idempotency_key', models.CharField(blank=True, max_length=150, verbose_name='chave de idempotência')),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='erro')),
            ],
            options={
                'verbose_name': 'e-mail enviado',
                'verbose_name_plural': 'e-mails enviados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_email', 'email_type', 'created_at'], name='notificatio_to_emai_224973_idx')],
            },
        ),
    ]
